# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- yaml_poc

pool:
  name: Default
#strategy:
#  matrix:
#    node_16_x:
#      node_version: 16.x
#    node_17_x:
#      node_version: 17.x

jobs:
- job: first_mock_job
  steps:
  - bash: echo "this is the first job that does nothing more than this message"
- job: actual_job
  steps:
  - task: NodeTool@0
    inputs:
      #versionSpec: $(node_version)
      versionSpec: 17.x
    displayName: 'Install Node.js'
  - script: |
      pwd
      ls -la
      cd ./mock-aut-testing-fw
      npm install
      npm run test_junit
    displayName: 'npm install and test'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-results.xml'
- job: third_mock_job
  steps:
  - bash: echo "this is the third job that does nothing more than this message"

